-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Job"
(
    id serial NOT NULL,
    name text NOT NULL,
    company_id serial NOT NULL,
    created_at timestamp without time zone NOT NULL,
    tag_ids integer[] NOT NULL,
    address text NOT NULL,
    salary_range text NOT NULL,
    top_reasons text NOT NULL,
    job_description text NOT NULL,
    skills_and_exp text NOT NULL,
    why_working_here text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Company"
(
    id serial NOT NULL,
    name text NOT NULL,
    address text NOT NULL,
    working_time text NOT NULL,
    employee_range text NOT NULL,
    "is_OT" boolean NOT NULL,
    country text NOT NULL,
    overview text NOT NULL,
    key_skill_ids integer[],
    why_working_here text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."User"
(
    id serial NOT NULL,
    username text,
    password text NOT NULL,
    email text NOT NULL,
    cover_letter text,
    avatar text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."User_Review_Company"
(
    user_id serial NOT NULL,
    company_id serial NOT NULL,
    id serial NOT NULL,
    salary_benefits_rating integer NOT NULL,
    training_learning_rating integer NOT NULL,
    management_cares_rating integer NOT NULL,
    culture_fun_rating integer NOT NULL,
    office_workspace_rating integer NOT NULL,
    what_i_liked text NOT NULL,
    title text NOT NULL,
    is_recommend boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    suggestion_improvement text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."User_Saved_Job"
(
    user_id serial NOT NULL,
    job_id serial NOT NULL,
    PRIMARY KEY (job_id, user_id)
);

CREATE TABLE IF NOT EXISTS public."User_Appied_Job"
(
    user_id serial NOT NULL,
    job_id serial NOT NULL,
    name text NOT NULL,
    cv text NOT NULL,
    description text,
    PRIMARY KEY (user_id, job_id)
);

ALTER TABLE public."User_Review_Company"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."User" (id)
    NOT VALID;


ALTER TABLE public."User_Review_Company"
    ADD FOREIGN KEY (company_id)
    REFERENCES public."Company" (id)
    NOT VALID;


ALTER TABLE public."User_Saved_Job"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."User" (id)
    NOT VALID;


ALTER TABLE public."User_Saved_Job"
    ADD FOREIGN KEY (job_id)
    REFERENCES public."Job" (id)
    NOT VALID;


ALTER TABLE public."User_Appied_Job"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."User" (id)
    NOT VALID;


ALTER TABLE public."User_Appied_Job"
    ADD FOREIGN KEY (job_id)
    REFERENCES public."Job" (id)
    NOT VALID;

END;